"""initial schema

Revision ID: a69f66dda688
Revises: 
Create Date: 2026-09-26 21:15:58.496276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a69f66dda688'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Application ids use a database sequence (APP-{SCHEME}-{YEAR}-{seq:06d}); autogenerate does not emit it.
    op.execute(sa.schema.CreateSequence(sa.Sequence("application_seq", start=1)))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assist_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mitra_user_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('scope', sa.Enum('UPLOAD_DOCUMENTS', 'VIEW_STATUS', 'RESPOND_DEFICIENCY', name='mitra_scope'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_STUDENT_OTP', 'ACTIVE', 'ENDED', name='assist_session_status'), nullable=False),
    sa.Column('student_otp_verified', sa.Boolean(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assist_sessions_mitra_user_id'), 'assist_sessions', ['mitra_user_id'], unique=False)
    op.create_index(op.f('ix_assist_sessions_student_id'), 'assist_sessions', ['student_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('assist_session_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_assist_session_id'), 'audit_log', ['assist_session_id'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_student_id'), 'audit_log', ['student_id'], unique=False)
    op.create_table('households',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('guardian_name', sa.String(), nullable=False),
    sa.Column('guardian_phone', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('template_key', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('PUSH', 'SMS', 'IVR', 'WHATSAPP', 'JAGO', 'EMAIL', name='notification_channel'), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', 'channel', name='uq_notification_once')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_student_id'), 'notifications', ['student_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('otp_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('purpose', sa.Enum('LOGIN', 'MITRA_CONSENT', name='otp_purpose'), nullable=False),
    sa.Column('subject_ref', sa.String(length=36), nullable=True),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_phone'), 'otp_challenges', ['phone'], unique=False)
    op.create_table('outbound_sms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('to_phone', sa.String(length=15), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_sms_to_phone'), 'outbound_sms', ['to_phone'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_outbox_published_at'), 'outbox', ['published_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'GUARDIAN', 'MITRA', 'INSTITUTE_OFFICER', 'DISTRICT_OFFICER', 'STATE_OFFICER', 'MINISTRY', name='user_role'), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('household_id', sa.String(), nullable=True),
    sa.Column('jurisdiction_state', sa.String(), nullable=True),
    sa.Column('jurisdiction_district', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('name_variants', sa.JSON(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('tribe', sa.String(), nullable=True),
    sa.Column('pvtg_flag', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('household_id', sa.String(), nullable=True),
    sa.Column('aadhaar_ref_token', sa.String(), nullable=True),
    sa.Column('apaar_id', sa.String(), nullable=True),
    sa.Column('nta_roll_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_ref_token'),
    sa.UniqueConstraint('apaar_id')
    )
    op.create_index(op.f('ix_students_household_id'), 'students', ['household_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('scheme', sa.Enum('PRE_MATRIC', 'POST_MATRIC', 'TOP_CLASS', 'NFST', 'NOS', name='scheme_type'), nullable=False),
    sa.Column('academic_year', sa.String(length=7), nullable=False),
    sa.Column('source_system', sa.Enum('NSP', 'SFMP', 'NOS_PORTAL', 'SCHOLARSETU', name='source_system'), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('canonical_state', sa.Enum('DRAFT', 'SUBMITTED', 'INSTITUTE_VERIFICATION', 'DEFICIENCY_RAISED', 'RESUBMITTED', 'AUTHORITY_VERIFICATION', 'SANCTIONED', 'REJECTED', 'PAYMENT_INITIATED', 'CREDITED', 'PAYMENT_FAILED', 'RENEWAL_DUE', name='canonical_state'), nullable=False),
    sa.Column('state_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('provisional_flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq'),
    sa.UniqueConstraint('source_system', 'source_ref', name='uq_application_source_ref')
    )
    op.create_index('idx_app_scheme_year', 'applications', ['scheme', 'academic_year'], unique=False)
    op.create_index(op.f('ix_applications_canonical_state'), 'applications', ['canonical_state'], unique=False)
    op.create_index(op.f('ix_applications_student_id'), 'applications', ['student_id'], unique=False)
    op.create_table('attestations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('claim_type', sa.Enum('IDENTITY', 'ST_STATUS', 'INCOME', 'DOMICILE', 'SCHOOL_ENROLMENT', 'HIGHER_ED', 'ACADEMIC_RECORDS', 'NET_JRF', 'DISABILITY', 'TOP_CLASS_INSTITUTION', 'FOREIGN_ADMISSION', name='claim_type'), nullable=False),
    sa.Column('claim_value', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('method', sa.Enum('API', 'OCR_ASSISTED', 'DOCUMENT', 'MANUAL', name='verification_method'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_hash', sa.String(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PROVISIONAL', 'EXPIRED', 'REVOKED', name='attestation_status'), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attest_student_claim_status', 'attestations', ['student_id', 'claim_type', 'status'], unique=False)
    op.create_table('wallet_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('issuer_signed', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_documents_student_id'), 'wallet_documents', ['student_id'], unique=False)
    op.create_table('deficiencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('raised_by_role', sa.String(), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deficiencies_application_id'), 'deficiencies', ['application_id'], unique=False)
    op.create_table('ledger_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('scheme', sa.Enum('PRE_MATRIC', 'POST_MATRIC', 'TOP_CLASS', 'NFST', 'NOS', name='scheme_type'), nullable=False),
    sa.Column('source', sa.Enum('NSP', 'SFMP', 'NOS_PORTAL', 'SCHOLARSETU', name='source_system'), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('hash_prev', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('application_id', 'sequence_no', name='uq_ledger_app_seq'),
    sa.UniqueConstraint('position')
    )
    op.create_index(op.f('ix_ledger_events_student_id'), 'ledger_events', ['student_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('instalment', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('state', sa.Enum('SCHEDULED', 'INITIATED', 'CREDITED', 'FAILED', 'RETRYING', name='payment_state'), nullable=False),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('pfms_ref', sa.String(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'instalment', name='uq_payment_instalment')
    )
    op.create_index(op.f('ix_payments_application_id'), 'payments', ['application_id'], unique=False)
    op.create_table('review_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('claim_type', sa.Enum('IDENTITY', 'ST_STATUS', 'INCOME', 'DOMICILE', 'SCHOOL_ENROLMENT', 'HIGHER_ED', 'ACADEMIC_RECORDS', 'NET_JRF', 'DISABILITY', 'TOP_CLASS_INSTITUTION', 'FOREIGN_ADMISSION', name='claim_type'), nullable=False),
    sa.Column('verification_status', sa.Enum('VERIFIED', 'PROVISIONAL', 'FAILED', 'SOURCE_UNAVAILABLE', 'MANUAL_REVIEW', 'PENDING', 'IN_PROGRESS', name='verification_status'), nullable=False),
    sa.Column('reason', sa.Enum('IDENTITY_NOT_CONFIRMED', 'NOT_CONFIRMED_BY_SOURCE', 'SOURCE_UNAVAILABLE', 'NO_AUTOMATED_SOURCE', name='review_reason'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('identity_score', sa.Float(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('attestation_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INFO_REQUESTED', 'APPROVED', 'REJECTED', 'RESOLVED_BY_SOURCE', name='review_case_status'), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', 'REQUEST_INFO', name='review_decision'), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('decision_event_id', sa.String(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attestation_id'], ['attestations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_open', 'review_cases', ['student_id', 'application_id', 'claim_type', 'status'], unique=False)
    op.create_index(op.f('ix_review_cases_application_id'), 'review_cases', ['application_id'], unique=False)
    op.create_index(op.f('ix_review_cases_status'), 'review_cases', ['status'], unique=False)
    op.create_index(op.f('ix_review_cases_student_id'), 'review_cases', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_cases_student_id'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_status'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_application_id'), table_name='review_cases')
    op.drop_index('idx_review_open', table_name='review_cases')
    op.drop_table('review_cases')
    op.drop_index(op.f('ix_payments_application_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_ledger_events_student_id'), table_name='ledger_events')
    op.drop_table('ledger_events')
    op.drop_index(op.f('ix_deficiencies_application_id'), table_name='deficiencies')
    op.drop_table('deficiencies')
    op.drop_index(op.f('ix_wallet_documents_student_id'), table_name='wallet_documents')
    op.drop_table('wallet_documents')
    op.drop_index('idx_attest_student_claim_status', table_name='attestations')
    op.drop_table('attestations')
    op.drop_index(op.f('ix_applications_student_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_canonical_state'), table_name='applications')
    op.drop_index('idx_app_scheme_year', table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_students_household_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_outbox_published_at'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_outbound_sms_to_phone'), table_name='outbound_sms')
    op.drop_table('outbound_sms')
    op.drop_index(op.f('ix_otp_challenges_phone'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_student_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('households')
    op.drop_index(op.f('ix_audit_log_student_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_assist_session_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_assist_sessions_student_id'), table_name='assist_sessions')
    op.drop_index(op.f('ix_assist_sessions_mitra_user_id'), table_name='assist_sessions')
    op.drop_table('assist_sessions')
    # ### end Alembic commands ###
    op.execute(sa.schema.DropSequence(sa.Sequence("application_seq")))
    for enum_name in ("user_role", "otp_purpose", "mitra_scope", "assist_session_status", "gender", "scheme_type",
                      "source_system", "canonical_state", "payment_state", "claim_type", "verification_method",
                      "attestation_status", "verification_status", "review_reason", "review_case_status",
                      "review_decision", "notification_channel"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
