"""eligibility rules and guideline corpus

Revision ID: 0002
Revises: a69f66dda688
Create Date: 2026-09-26 21:36:06.672240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = 'a69f66dda688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guideline_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scheme', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_title', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('effective', sa.String(), nullable=False),
    sa.Column('corpus_version', sa.String(length=64), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', section), 'A') || setweight(to_tsvector('english', text), 'B')", persisted=True), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_guideline_tsv', 'guideline_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_guideline_chunks_corpus_version'), 'guideline_chunks', ['corpus_version'], unique=False)
    op.create_index(op.f('ix_guideline_chunks_scheme'), 'guideline_chunks', ['scheme'], unique=False)
    op.create_table('rule_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scheme', postgresql.ENUM('PRE_MATRIC', 'POST_MATRIC', 'TOP_CLASS', 'NFST', 'NOS', name='scheme_type', create_type=False), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('decision_table', sa.JSON(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scheme', 'version', 'effective_from', name='uq_rule_version')
    )
    op.create_table('eligibility_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('scheme', postgresql.ENUM('PRE_MATRIC', 'POST_MATRIC', 'TOP_CLASS', 'NFST', 'NOS', name='scheme_type', create_type=False), nullable=False),
    sa.Column('rule_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('missing', sa.JSON(), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_decisions_student_id'), 'eligibility_decisions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eligibility_decisions_student_id'), table_name='eligibility_decisions')
    op.drop_table('eligibility_decisions')
    op.drop_table('rule_versions')
    op.drop_index(op.f('ix_guideline_chunks_scheme'), table_name='guideline_chunks')
    op.drop_index(op.f('ix_guideline_chunks_corpus_version'), table_name='guideline_chunks')
    op.drop_index('idx_guideline_tsv', table_name='guideline_chunks', postgresql_using='gin')
    op.drop_table('guideline_chunks')
    # ### end Alembic commands ###
