"""consent dbt guardian adapters institution codes

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-27 01:02:25.674407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parked_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_system', postgresql.ENUM('NSP', 'SFMP', 'NOS_PORTAL', 'SCHOLARSETU', name='source_system', create_type=False), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=False),
    sa.Column('raw_status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parked_events_created_at'), 'parked_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_parked_events_source_ref'), 'parked_events', ['source_ref'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('requester', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('data_items', sa.JSON(), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_student_id'), 'consents', ['student_id'], unique=False)
    op.create_table('dbt_health_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('bank_account_masked', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbt_health_checks_application_id'), 'dbt_health_checks', ['application_id'], unique=False)
    op.create_index(op.f('ix_dbt_health_checks_created_at'), 'dbt_health_checks', ['created_at'], unique=False)
    op.create_index(op.f('ix_dbt_health_checks_student_id'), 'dbt_health_checks', ['student_id'], unique=False)
    op.create_table('dbt_retries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('health_check_id', sa.String(length=36), nullable=True),
    sa.Column('pfms_ref', sa.String(), nullable=True),
    sa.Column('failure_code', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['health_check_id'], ['dbt_health_checks.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dbt_retries_payment_id'), 'dbt_retries', ['payment_id'], unique=False)
    op.add_column('users', sa.Column('institution_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'institution_code')
    op.drop_index(op.f('ix_dbt_retries_payment_id'), table_name='dbt_retries')
    op.drop_table('dbt_retries')
    op.drop_index(op.f('ix_dbt_health_checks_student_id'), table_name='dbt_health_checks')
    op.drop_index(op.f('ix_dbt_health_checks_created_at'), table_name='dbt_health_checks')
    op.drop_index(op.f('ix_dbt_health_checks_application_id'), table_name='dbt_health_checks')
    op.drop_table('dbt_health_checks')
    op.drop_index(op.f('ix_consents_student_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_parked_events_source_ref'), table_name='parked_events')
    op.drop_index(op.f('ix_parked_events_created_at'), table_name='parked_events')
    op.drop_table('parked_events')
    # ### end Alembic commands ###
