"""Add email login support

Revision ID: fc89618e1774
Revises: 0009
Create Date: 2026-10-01 19:59:41.936692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc89618e1774'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_challenges', sa.Column('email', sa.String(length=120), nullable=True))
    op.alter_column('otp_challenges', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.create_index(op.f('ix_otp_challenges_email'), 'otp_challenges', ['email'], unique=False)
    op.create_index('ix_otp_challenges_email_purpose_created', 'otp_challenges', ['email', 'purpose', 'created_at'], unique=False)
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('users', 'email')
    op.drop_index('ix_otp_challenges_email_purpose_created', table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_email'), table_name='otp_challenges')
    op.alter_column('otp_challenges', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('otp_challenges', 'email')
    # ### end Alembic commands ###
