"""Deterministic response templates for money-safe AI.

Factual data (amounts, dates, statuses) are ONLY inserted through these templates,
never generated by the LLM.
"""

RESPONSE_TEMPLATES = {
    "status_update": {
        "en": "Your {scheme_name} application ({app_id}) is currently in '{status}' stage. {next_action}",
        "hi": "आपका {scheme_name} आवेदन ({app_id}) वर्तमान में '{status}' चरण में है। {next_action}"
    },
    "payment_summary": {
        "en": "For {scheme_name} ({academic_year}):\n- Sanctioned: ₹{sanctioned}\n- Credited: ₹{credited}\n- Pending: ₹{pending}\n{status_detail}",
        "hi": "{scheme_name} ({academic_year}) के लिए:\n- स्वीकृत: ₹{sanctioned}\n- जमा: ₹{credited}\n- लंबित: ₹{pending}\n{status_detail}"
    },
    "eligibility_result": {
        "en": "Eligibility check for {scheme_name}:\nResult: {result}\n{reasons}",
        "hi": "{scheme_name} के लिए पात्रता जांच:\nपरिणाम: {result}\n{reasons}"
    },
    "no_data": {
        "en": "I don't have this information right now. Please contact the helpline at {helpline_number} or visit your institute's scholarship cell.",
        "hi": "यह जानकारी अभी मेरे पास उपलब्ध नहीं है। कृपया हेल्पलाइन {helpline_number} पर संपर्क करें या अपने संस्थान के छात्रवृत्ति प्रकोष्ठ पर जाएं।"
    },
    "deficiency_explanation": {
        "en": "Deficiency: {description}\nSteps to fix:\n{fix_steps}\nDeadline: {deadline}",
        "hi": "कमी: {description}\nसुधार के चरण:\n{fix_steps}\nअंतिम तिथि: {deadline}"
    },
    "greeting": {
        "en": "Hello! I'm JAGO, your scholarship assistant. I can help you check your application status, payments, eligibility, and more. How can I help?",
        "hi": "नमस्ते! मैं जागो हूं, आपका छात्रवृत्ति सहायक। मैं आपके आवेदन की स्थिति, भुगतान, पात्रता और अन्य जानकारी में मदद कर सकता हूं। कैसे मदद करूं?"
    }
}

# Status descriptions in plain language
STATUS_DESCRIPTIONS = {
    "DRAFT": {"en": "Draft (not yet submitted)", "hi": "ड्राफ्ट (अभी तक जमा नहीं किया)"},
    "SUBMITTED": {"en": "Submitted, awaiting institute verification", "hi": "जमा किया गया, संस्थान सत्यापन की प्रतीक्षा में"},
    "INSTITUTE_VERIFICATION": {"en": "Being verified by your institute", "hi": "आपके संस्थान द्वारा सत्यापित किया जा रहा है"},
    "AUTHORITY_VERIFICATION": {"en": "Being verified by the district/state authority", "hi": "जिला/राज्य प्राधिकरण द्वारा सत्यापित किया जा रहा है"},
    "DEFICIENCY_RAISED": {"en": "Action needed - a deficiency has been raised", "hi": "कार्रवाई आवश्यक - एक कमी पाई गई है"},
    "SANCTIONED": {"en": "Sanctioned! Payment will be processed soon", "hi": "स्वीकृत! भुगतान जल्द ही संसाधित किया जाएगा"},
    "PAYMENT_INITIATED": {"en": "Payment has been initiated", "hi": "भुगतान शुरू किया गया है"},
    "CREDITED": {"en": "Payment credited to your bank account", "hi": "भुगतान आपके बैंक खाते में जमा किया गया"},
    "PAYMENT_FAILED": {"en": "Payment failed - action needed", "hi": "भुगतान विफल - कार्रवाई आवश्यक"},
    "REJECTED": {"en": "Application rejected", "hi": "आवेदन अस्वीकृत"},
    "RENEWAL_DUE": {"en": "Renewal is due for next year", "hi": "अगले वर्ष के लिए नवीनीकरण बकाया है"},
}

DEFICIENCY_EXPLANATIONS = {
    "INCOME_CERT_EXPIRED": {
        "en": "Your income certificate has expired. You need a new one for the current financial year.",
        "hi": "आपका आय प्रमाण पत्र समाप्त हो गया है। आपको चालू वित्तीय वर्ष का नया प्रमाण पत्र चाहिए।",
        "fix_steps": ["Visit your district office or e-District portal", "Apply for a new income certificate", "Upload the new certificate"]
    },
    "ST_CERT_MISSING": {
        "en": "Your Scheduled Tribe certificate is missing or could not be verified.",
        "hi": "आपका अनुसूचित जनजाति प्रमाण पत्र गायब है या सत्यापित नहीं हो सका।",
        "fix_steps": ["Check if your caste certificate is on DigiLocker", "If not, upload a scanned copy", "Ensure it's issued by a competent authority"]
    },
    "BANK_DETAILS_MISMATCH": {
        "en": "Bank account details don't match your identity records.",
        "hi": "बैंक खाते का विवरण आपके पहचान रिकॉर्ड से मेल नहीं खाता।",
        "fix_steps": ["Check the name on your bank passbook", "Ensure it matches your Aadhaar name", "Visit bank if correction needed"]
    },
    "MARKSHEET_MISSING": {
        "en": "Previous year's marksheet/academic record is required.",
        "hi": "पिछले वर्ष की मार्कशीट/शैक्षणिक रिकॉर्ड आवश्यक है।",
        "fix_steps": ["Check DigiLocker for your marksheet", "Contact your previous school/college for a copy", "Upload a clear scanned copy"]
    },
    "ENROLMENT_NOT_VERIFIED": {
        "en": "Your current school/college enrolment could not be verified.",
        "hi": "आपके वर्तमान विद्यालय/महाविद्यालय में नामांकन सत्यापित नहीं हो सका।",
        "fix_steps": ["Ask your institute to confirm your enrolment in the system", "Ensure your AISHE/UDISE code is correct", "Contact your scholarship nodal officer"]
    }
}
