"""Regenerate docs/RULE_VALUES_TO_VERIFY.md from rules/*.json (run after editing any rule file)."""

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


def fmt(value) -> str:
    if value is None:
        return "—"
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False).replace("|", "/")
    return f"{value:,}" if isinstance(value, int) else str(value)


def main() -> None:
    rows, conflicts = [], []
    for path in sorted((REPO / "rules").glob("*.json")):
        table = json.loads(path.read_text())
        for section in ("parameters", "amounts"):
            for name, p in table.get(section, {}).items():
                official = p.get("official_document_value")
                row = (table["scheme"], f"{section}.{name}", fmt(p["value"]), p.get("unit", ""),
                       fmt(official) if official is not None else "not stated separately",
                       "**CONFLICT**" if p.get("conflict") else ("match" if official is not None else "check"),
                       f"[{p['source']}]({p['source_url']})", p.get("note", ""))
                rows.append(row)
                if p.get("conflict") or (official is None and p["value"] is None):
                    conflicts.append(row)
    header = "| Scheme | Parameter | Value used now | Unit | Official document says | Status | Source | Note |\n|---|---|---|---|---|---|---|---|\n"
    def lines(rs):
        return "".join("| " + " | ".join(r) + " |\n" for r in rs)
    doc = f"""# Scheme values to verify

Generated by `scripts/rule_values_report.py` from `rules/*.json`. Do not edit by hand.

Every scheme parameter lives in exactly one place: the `parameters` / `amounts` blocks of
`rules/*.json`. The eligibility engine and the seed data read them from there; JAGO quotes the
official guideline text itself.

**Nothing here has been verified by the team** (`verified_by_team: false` everywhere). The numbers in
use are the values the team originally entered; they were **not changed**. Where the official document
states something different, it is shown next to it. The team must decide each conflict (and cite the
order that applies), then update the rule file under a **new version** and set `verified_by_team: true`.

Official documents consulted (downloaded and hashed in
`services/core/app/jago_skill/guidelines/sources.json`):

- Pre-Matric guidelines, effective 01-07-2012 — scholarships.gov.in
- Post-Matric regulation, applicable from 01-04-2022 — scholarships.gov.in
- National Fellowship & Scholarship (NFST Part A, Top Class Part B), 2021-22 to 2025-26 — tribal.nic.in
- National Overseas Scholarship, 2021-22 to 2025-26 — tribal.nic.in

Note that the Pre-Matric guideline is from 2012; a PIB release (PRID 1907241) cites higher figures
(Rs 2.50 lakh income ceiling; Rs 225/525 per month), which suggests a later revision the team should obtain.

## Conflicts to resolve first ({len(conflicts)})

{header}{lines(conflicts)}
## All values ({len(rows)})

{header}{lines(rows)}"""
    (REPO / "docs" / "RULE_VALUES_TO_VERIFY.md").write_text(doc, encoding="utf-8")
    print(f"wrote docs/RULE_VALUES_TO_VERIFY.md: {len(rows)} values, {len(conflicts)} conflicts")


if __name__ == "__main__":
    main()
